<a href="https://colab.research.google.com/github/naimur-29/machine-learning/blob/main/pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


## Introductions to Tensors

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [4]:
scalar.ndim

0

In [5]:
# get tensor as python numbers
scalar.item()

3

In [6]:
# vector
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector.ndim

1

In [9]:
# MATRIX
matrix = torch.tensor([
    [9, 9],
    [7, 7]
])
matrix, matrix.ndim, matrix.shape

(tensor([[9, 9],
         [7, 7]]), 2, torch.Size([2, 2]))

In [10]:
matrix[1][0].item()

7

In [11]:
# TENSOR
tnsr = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])
tnsr, tnsr.ndim, tnsr.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), 3, torch.Size([1, 3, 3]))

### Random Tensors

In [12]:
# Creating random tensors

random_tensor = torch.rand(3, 4, 7)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[[0.0274, 0.0702, 0.9528, 0.2110, 0.2881, 0.0064, 0.6964],
          [0.1042, 0.4843, 0.7035, 0.7599, 0.2766, 0.6344, 0.5007],
          [0.0902, 0.1181, 0.7899, 0.7291, 0.5532, 0.9248, 0.3696],
          [0.0982, 0.7678, 0.0077, 0.1005, 0.0805, 0.0940, 0.8402]],
 
         [[0.7882, 0.7830, 0.1496, 0.0662, 0.0679, 0.7492, 0.2926],
          [0.9964, 0.5192, 0.6673, 0.1435, 0.7040, 0.9346, 0.6058],
          [0.9066, 0.6237, 0.2982, 0.2099, 0.4070, 0.3661, 0.4030],
          [0.4544, 0.4196, 0.6432, 0.2328, 0.5166, 0.2903, 0.2042]],
 
         [[0.2476, 0.3031, 0.6157, 0.2880, 0.9677, 0.4314, 0.3916],
          [0.1267, 0.6856, 0.4106, 0.0368, 0.4735, 0.0448, 0.1949],
          [0.8457, 0.9056, 0.0489, 0.1978, 0.2356, 0.5871, 0.4657],
          [0.4446, 0.3653, 0.0175, 0.2656, 0.9864, 0.2056, 0.7787]]]),
 3,
 torch.Size([3, 4, 7]))

In [13]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros & Ones

In [14]:
# create a tensor of all zeros
zeros = torch.zeros(size=(2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones*10

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [16]:
ones.dtype

torch.float32

In [17]:
zeros.matmul(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors & tensor-likes

In [18]:
# use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
torch.zeros(size=(3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ranged_tensor = torch.arange(start=0, end=100, step=10)

In [21]:
# creating tensor-likes
torch.zeros_like(input=ranged_tensor)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])