<a href="https://colab.research.google.com/github/naimur-29/machine-learning/blob/main/pytorch/pytorch_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics

In [1]:
import torch

In [2]:
x = torch.empty(2, 2, 2, 3)
x

tensor([[[[-1.5242e+03,  4.5699e-41, -5.2232e+24],
          [ 4.5699e-41, -5.0683e+24,  4.5699e-41]],

         [[-8.9353e+04,  4.5699e-41,  1.4464e-15],
          [ 4.5699e-41,  0.0000e+00,  4.5699e-41]]],


        [[[-4.9093e+22,  4.5699e-41, -8.9428e+04],
          [ 4.5699e-41, -8.9354e+04,  4.5699e-41]],

         [[-8.8285e+04,  4.5699e-41, -8.8287e+04],
          [ 4.5699e-41, -1.5241e+03,  4.5699e-41]]]])

In [3]:
torch.rand(2, 2)

tensor([[0.0344, 0.1779],
        [0.2290, 0.1041]])

In [4]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
x.dtype

torch.float32

In [7]:
x = torch.ones(3, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
x.shape, x.ndim

(torch.Size([3, 4]), 2)

In [9]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

x, y

(tensor([[0.6638, 0.5404],
         [0.2274, 0.8312]]), tensor([[0.2644, 0.2039],
         [0.1267, 0.0105]]))

In [10]:
z = x + y
z

tensor([[0.9282, 0.7443],
        [0.3541, 0.8417]])

In [11]:
y.add_(x)
y

tensor([[0.9282, 0.7443],
        [0.3541, 0.8417]])

In [12]:
torch.mul(x, y)

tensor([[0.6162, 0.4022],
        [0.0805, 0.6997]])

In [13]:
x, y, torch.div(x, y)

(tensor([[0.6638, 0.5404],
         [0.2274, 0.8312]]), tensor([[0.9282, 0.7443],
         [0.3541, 0.8417]]), tensor([[0.7152, 0.7260],
         [0.6422, 0.9875]]))

In [14]:
x[:, 0]

tensor([0.6638, 0.2274])

In [15]:
x = torch.rand(4, 4)
x

tensor([[0.9948, 0.8211, 0.8179, 0.2436],
        [0.2446, 0.3395, 0.0072, 0.0802],
        [0.4474, 0.8964, 0.7336, 0.7134],
        [0.5084, 0.3609, 0.0756, 0.0950]])

In [16]:
y = x.view(-1, 8)
y, y.size()

(tensor([[0.9948, 0.8211, 0.8179, 0.2436, 0.2446, 0.3395, 0.0072, 0.0802],
         [0.4474, 0.8964, 0.7336, 0.7134, 0.5084, 0.3609, 0.0756, 0.0950]]),
 torch.Size([2, 8]))

## Converting Numpy to Tensors

In [17]:
import numpy as np

In [18]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [19]:
b = a.numpy()
b, type(b)

(array([1., 1., 1., 1., 1.], dtype=float32), numpy.ndarray)

In [20]:
# same memory loaction:
a.mul_(10)
a, b

(tensor([10., 10., 10., 10., 10.]),
 array([10., 10., 10., 10., 10.], dtype=float32))

In [21]:
a = np.ones(5)
a, type(a)

(array([1., 1., 1., 1., 1.]), numpy.ndarray)

In [22]:
b = torch.from_numpy(a)
b, type(b)

(tensor([1., 1., 1., 1., 1.], dtype=torch.float64), torch.Tensor)

In [24]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y

z
# z = z.to("cpu")
# z.numpy()

tensor([[0.9282, 0.7443],
        [0.3541, 0.8417]])

In [25]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [29]:
x = torch.rand(5, requires_grad=True)
x

tensor([0.7851, 0.9357, 0.3736, 0.3970, 0.8976], requires_grad=True)

In [30]:
# Autograd
x = torch.randn(3)
x

tensor([-0.6413,  0.8006,  1.7767])