In [298]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

In [299]:
# load datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [300]:
# split in features & labels
x = iris.data
y = iris.target
print(x, y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [301]:
x.shape, y.shape

((150, 4), (150,))

In [302]:
# splitting dataset into tain & test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(x_train, y_train, '\n')
print(x_test, y_test)

[[6.3 2.8 5.1 1.5]
 [6.1 2.9 4.7 1.4]
 [5.3 3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [4.6 3.4 1.4 0.3]
 [6.8 3.  5.5 2.1]
 [4.8 3.  1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.8 2.6 4.  1.2]
 [6.7 2.5 5.8 1.8]
 [4.9 3.1 1.5 0.1]
 [6.7 3.  5.2 2.3]
 [7.6 3.  6.6 2.1]
 [5.6 2.9 3.6 1.3]
 [6.  2.2 4.  1. ]
 [6.9 3.1 4.9 1.5]
 [6.  2.2 5.  1.5]
 [5.9 3.  5.1 1.8]
 [5.1 3.8 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [5.  3.5 1.6 0.6]
 [6.4 2.9 4.3 1.3]
 [5.8 2.7 5.1 1.9]
 [5.  3.4 1.6 0.4]
 [6.5 3.2 5.1 2. ]
 [5.7 4.4 1.5 0.4]
 [6.  2.7 5.1 1.6]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.5 0.3]
 [5.4 3.9 1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [6.7 3.1 5.6 2.4]
 [5.  3.4 1.5 0.2]
 [7.1 3.  5.9 2.1]
 [4.9 2.5 4.5 1.7]
 [7.2 3.  5.8 1.6]
 [6.9 3.1 5.4 2.1]
 [5.6 2.7 4.2 1.3]
 [5.8 4.  1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [5.  3.6 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [6.3 2.5 4.9 1.5]
 [5.1 3.7 1.5 0.4]
 [6.  3.  4.8 1.8]
 [5.7 2.5 5.  2. ]
 [6.4 2.8 5.6 2.1]
 [4.9 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.2]
 [7.7 3.8 6.7 2.2]
 [4.3 3.  1.1 0.1]
 [5.8 2.7 3.

In [303]:
classes = {
    0: 'Iris Setosa',
    1: 'Iris Versicolour',
    2: 'Iris Verginica'
}

In [304]:
#SVM --> Support Vector Machine
from sklearn import svm
from sklearn.metrics import accuracy_score

In [305]:
# creating model & training
model = svm.SVC()
model.fit(x_train, y_train)

predictions = model.predict(x_test)
acc = accuracy_score(y_test, predictions)

acc

1.0

In [309]:
#testing
data_no = 1
actual = y_test[data_no]
pred = model.predict([x_test[data_no]])

actual, pred[0]

(2, 2)

In [ ]:
#KNN
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
# load datasets
data = pd.read_csv("./drive/MyDrive/Machine Learning/scikit learn/data/car.data")
data.head()

In [ ]:
# check for empty data
data.isnull().sum()

In [ ]:
# splitting feature & label
X = data[[
    'buying',
    'maintanance',
    'safety'
]].values
Y = data[['class']]

X, Y

In [ ]:
# encoding data
label_encoder = LabelEncoder()
for i in range(len(X[0])):
  X[:, i] = label_encoder.fit_transform(X[:, i])

X

In [ ]:
# encoding label with mapping
label_mapping = {
    'unacc': 0,
    'acc': 1,
    'good': 2,
    'vgood': 3
}

Y['class'] = Y['class'].map(label_mapping)
Y = np.array(Y)
Y

In [ ]:
# separate data for train & testing
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
x_train,  y_train

In [ ]:
# create model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

#trainning
knn.fit(x_train, y_train)

prediction = knn.predict(x_test)
accuracy = metrics.accuracy_score(y_test, prediction)

print(prediction)
print(accuracy)

In [ ]:
print("actual_value", Y[-1])
print("predicted_value", knn.predict(X)[-1])